### ISSUE TITLE
Error in wget-fetch for my JDBC driver

### ISSUE THREAD

**Issue by jjuarez** [autostructure/artifactory#1]
Hi, I´m trying to use this module, but a have an upset error, the execution of the wget wrapper, are you sure about the correcto operation of the puppet's URL like:
`puppet:///modules/my_resources/artifactory/mysql-connector-java-5.1.40-bin.jar`

the logs of the puppet execution seems good...
`
Info: Using configured environment 'development'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for artifactory-dev-1.4iq.vm
Info: Applying configuration version '1480961869'
Notice: /Stage[main]/Artifactory::Config/Wget::Fetch[puppet://modules/resources_4iq/artifactory/mysql-connector-java-5.1.40-bin.jar]/Exec[wget-puppet://modules/resources_4iq/artifactory/mysql-connector-java-5.1.40-bin.jar]/returns: executed successfully
Info: Class[Artifactory::Config]: Scheduling refresh of Class[Artifactory::Service]
Info: Class[Artifactory::Service]: Scheduling refresh of Service[artifactory]
Notice: /Stage[main]/Artifactory::Service/Service[artifactory]: Triggered 'refresh' from 1 events
Notice: Applied catalog in 8.31 seconds
`
but the *file size is 0*

**Comment by bryanjbelanger-puppet** [comment]
If you test the URL on a stand-alone test manifest does it work?

Bryan Belanger | Principal Consultant

Autostructure: www.autostructure.io<http://www.autostructure.io/>

phone: +1 (248) 690-6565 | email: bryan@autostructure.io<mailto:bryan@autostructure.io>

On Dec 5, 2016, at 11:31 AM, Javier Juarez <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I´m trying to use this module, but a have an upset error, the execution of the wget wrapper, are you sure about the correcto operation of the puppet's URL like:
puppet:///modules/my_resources/artifactory/mysql-connector-java-5.1.40-bin.jar

the logs of the puppet execution seems good...
Info: Using configured environment 'development' Info: Retrieving pluginfacts Info: Retrieving plugin Info: Loading facts Info: Caching catalog for artifactory-dev-1.4iq.vm Info: Applying configuration version '1480961869' Notice: /Stage[main]/Artifactory::Config/Wget::Fetch[puppet://modules/resources_4iq/artifactory/mysql-connector-java-5.1.40-bin.jar]/Exec[wget-puppet://modules/resources_4iq/artifactory/mysql-connector-java-5.1.40-bin.jar]/returns: executed successfully Info: Class[Artifactory::Config<puppet://modules/resources_4iq/artifactory/mysql-connector-java-5.1.40-bin.jar]/Exec[wget-puppet://modules/resources_4iq/artifactory/mysql-connector-java-5.1.40-bin.jar]/returns:%20executed%20successfully%20Info:%20Class[Artifactory::Config>]: Scheduling refresh of Class[Artifactory::Service] Info: Class[Artifactory::Service]: Scheduling refresh of Service[artifactory] Notice: /Stage[main]/Artifactory::Service/Service[artifactory]: Triggered 'refresh' from 1 events Notice: Applied catalog in 8.31 seconds
but the file size is 0

**Comment by alexjfisher** [comment]
@bryanjbelanger-puppet I've encountered this too.

The documentation suggests you can use
```
jdbc_driver_url => 'puppet://modules/my_module/mysql.jar'
```

but ever since switching from [staging to deploy](https://github.com/autostructure/artifactory/commit/1bd220fd8263b04990c53adacc3172059c7156c8), this hasn't been the case.  staging can fetch from [puppet://](https://github.com/voxpupuli/puppet-staging/blob/251b6fa5b42da9e1970b7a15d20fddfbd800d616/manifests/deploy.pp#L4) urls, wget can not.

**Comment by bryanjbelanger** [comment]
HI Alex.

You are missing a '/' in your URL. It is 'puppet:///m...', not 'puppet://m...'.

If you continue to have a problem I will take a deeper look.

Thanks...

**Comment by alexjfisher** [comment]
That URL example was taken straight from the [README](https://github.com/autostructure/artifactory/blame/7f1b6280712f1cffe219dee9d76ea966c9ebf0d1/README.markdown#L48).  Either way, it will not work.  wget::fetch will not work with `puppet:///` urls.

I'm working on a PR to add a `manage_jdbc_driver` boolean parameter.  The idea being I'll then be able to use https://forge.puppet.com/puppet/mysql_java_connector in my artifactory profile.

**Comment by bryanjbelanger** [comment]
HI Alex,

I added a fix. I don't have time for full acceptance testing tonight.

'IF' your code is ready to go can you give it a quick run?

Thanks...

**Comment by alexjfisher** [comment]
@bryanjbelanger Thanks I'll be testing this today.

Your forge module upload for 2.0.10 looks funky. The permissions on `storage.properties.epp` have changed and my puppetmaster can no longer read the file.

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Permission denied - /etc/puppetlabs/code/environments/GIT_dev_artifactory/modules/artifactory/templates/storage.properties.epp at /etc/puppetlabs/code/environments/GIT_dev_artifactory/modules/artifactory/manifests/config.pp:21:20 on node artifactory01c.example.com
```

```
alex@alex-VirtualBox:~/test$ puppet module install --modulepath=/tmp/modules autostructure-artifactory --version 2.0.7
Notice: Preparing to install into /tmp/modules ...
Notice: Created target directory /tmp/modules
Notice: Downloading from https://forgeapi.puppet.com ...
Notice: Installing -- do not interrupt ...
/tmp/modules
└─┬ autostructure-artifactory (v2.0.7)
  ├── maestrodev-wget (v1.7.3)
  └─┬ puppetlabs-java (v1.6.0)
    └── puppetlabs-stdlib (v4.16.0)
alex@alex-VirtualBox:~/test$ ls -l /tmp/modules/artifactory/templates/storage.properties.epp
-rw-r--r-- 1 alex alex 3267 Aug 14  2016 /tmp/modules/artifactory/templates/storage.properties.epp
alex@alex-VirtualBox:~/test$ rm -rf /tmp/modules/artifactory
alex@alex-VirtualBox:~/test$ puppet module install --modulepath=/tmp/modules autostructure-artifactory
Notice: Preparing to install into /tmp/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Notice: Installing -- do not interrupt ...
/tmp/modules
└─┬ autostructure-artifactory (v2.0.10)
  ├── maestrodev-wget (v1.7.3)
  ├── puppetlabs-java (v1.6.0)
  └── puppetlabs-stdlib (v4.16.0)
alex@alex-VirtualBox:~/test$ ls -l /tmp/modules/artifactory/templates/storage.properties.epp
-rw-r----- 1 alex alex 3267 Mar 22 02:40 /tmp/modules/artifactory/templates/storage.properties.epp
```

Notice the world read permission has gone.

**Comment by alexjfisher** [comment]
@bryanjbelanger-puppet Having tested the change by downloading the module from git, not the forge, the fix you implemented works fine for me using a puppet:/// URL.

I encountered a separate issue with the database configuration file, and have opened https://github.com/autostructure/artifactory/pull/2 to fix that.

Thanks for you help.  I think this issue can be closed.
