### ISSUE TITLE
storage.properties.epp missing

### ISSUE THREAD

**Issue by winningpanthers** [autostructure/artifactory#13]
Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'artifactory/storage.properties.epp' at /etc/puppetlabs/code/environments/production/modules/artifactory_ha/manifests/config.pp:51:16 on node

**Comment by mijamill** [comment]
New release 2.0.6 addresses this issue. 'Storage.properties' is supposed to be referenced as 'db.properties' in config file.
